/* SKCT original practice bank factory — calibrated item families, never copies source wording. */
(function(root){
'use strict';
const AREAS=[['lang','언어이해'],['data','자료해석'],['math','창의수리'],['logic','언어추리'],['seq','수열추리']];
const rand=(a,b)=>b===undefined?Math.floor(Math.random()*a):Math.floor(Math.random()*(b-a+1))+a, pick=a=>a[rand(a.length)], shuffled=a=>{a=a.slice();for(let i=a.length-1;i>0;i--){let j=rand(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;};
function item(area,type,difficulty,q,choices,answer,explain,p=[],seq='') { return {area,q,passage:p.join('\n'),p,choices,answer,explain,qtype:type,difficulty,seq,fixedOrder:false}; }
function choices(answer, vals, fmt=x=>String(x)) { const seen=new Set([String(answer)]), wrong=[]; for(const v of vals){const s=String(v);if(!seen.has(s)){seen.add(s);wrong.push(v);} if(wrong.length===4)break;} let n=1;while(wrong.length<4){let v=typeof answer==='number'?answer+(n%2?1:-1)*Math.ceil(n/2):`${answer} (${n})`;n++;if(!seen.has(String(v))){seen.add(String(v));wrong.push(v);}} const a=shuffled([answer,...wrong]).map(fmt);return {choices:a,answer:a.indexOf(fmt(answer))}; }
const datasets=[
 {theme:'도시의 그늘',p:'도시의 가로수는 여름철 그늘을 제공하고 빗물이 땅으로 스며드는 것을 돕는다. 다만 뿌리가 보도블록을 밀어 올리는 문제를 줄이려면 수종만 고를 것이 아니라 토양 공간과 배수 구조를 함께 설계해야 한다. 최근에는 관리 비용만을 기준으로 나무를 줄이기보다, 그늘이 필요한 구간과 보행량을 함께 고려하는 방식이 주목받고 있다.',main:'가로수 정책은 수종 선택과 함께 주변 공간을 설계하고 이용 수요를 고려해야 한다.',wrong:['가로수의 뿌리 문제는 수종을 바꾸면 언제나 해결된다.','관리 비용이 크면 그늘 수요와 관계없이 나무를 없애야 한다.','도시의 빗물 관리는 가로수와 관련이 없다.','보행량이 많은 곳에는 가로수를 심지 않는 것이 원칙이다.'],detail:'토양 공간과 배수 구조를 함께 설계해야 뿌리로 인한 보도블록 문제를 줄일 수 있다.'},
 {theme:'기록의 의미',p:'기록은 과거를 그대로 보존하는 투명한 창이라기보다, 무엇을 남기고 어떤 순서로 배열할지 선택한 결과다. 같은 사건도 기록자의 목적과 사용된 분류 기준에 따라 서로 다른 모습으로 읽힐 수 있다. 따라서 자료를 활용할 때에는 내용뿐 아니라 작성 시점과 누락된 정보도 살펴야 한다.',main:'기록 자료는 작성자의 선택과 분류 기준을 고려해 비판적으로 읽어야 한다.',wrong:['기록은 과거의 모든 사실을 빠짐없이 담는다.','분류 기준이 달라도 기록의 해석은 달라지지 않는다.','작성 시점은 자료의 신뢰성과 무관하다.','기록에 포함되지 않은 정보는 존재하지 않았던 사실이다.'],detail:'자료를 활용할 때 작성 시점과 누락된 정보도 살펴야 한다.'},
 {theme:'공유 자전거',p:'공유 자전거의 대여소를 늘리면 이용 접근성이 좋아질 수 있지만, 설치 수만으로 이용 편의를 설명하기는 어렵다. 출퇴근 시간대의 수요와 자전거 재배치 빈도, 보행 동선과의 간섭도 함께 살펴야 한다. 한 지역의 대여소가 늘어도 자전거가 제때 채워지지 않으면 실제 이용률은 낮을 수 있다.',main:'공유 자전거의 성과는 대여소 수보다 운영과 수요 대응을 함께 평가해야 한다.',wrong:['대여소가 많을수록 실제 이용률은 반드시 높아진다.','자전거 재배치는 이용 편의와 관계가 없다.','출퇴근 시간대 수요는 대여소 위치와 무관하다.','보행 동선과의 간섭은 서비스 평가에 포함할 필요가 없다.'],detail:'자전거가 제때 채워지지 않으면 대여소가 늘어도 실제 이용률이 낮을 수 있다.'},
 {theme:'온라인 학습',p:'온라인 학습에서 영상 재생 시간을 늘리는 것만으로 학습 효과가 커지는 것은 아니다. 학습자는 내용을 확인하고 자신의 이해를 점검하는 활동이 필요하다. 짧은 설명 뒤에 문제를 풀고 피드백을 받도록 구성하면, 긴 강의를 연속해서 듣는 경우보다 학습자가 놓친 부분을 빠르게 확인할 수 있다.',main:'온라인 학습은 재생 시간보다 이해 점검과 피드백의 설계가 중요하다.',wrong:['영상이 길수록 학습 효과가 커진다.','학습자는 이해 점검 없이 강의를 반복 재생해야 한다.','문제 풀이와 피드백은 온라인 학습에 도움이 되지 않는다.','학습자의 이해 상태는 수업 설계에 반영할 수 없다.'],detail:'문제 풀이와 피드백은 학습자가 놓친 부분을 빠르게 확인하게 한다.'},
 {theme:'재사용 용기',p:'다회용기의 환경적 이점은 세척과 회수 과정까지 포함해 평가해야 한다. 한 번 사용한 용기를 회수하지 못하거나 먼 거리를 운송하면 기대했던 이점이 줄어들 수 있다. 반대로 회수 동선이 짧고 반복 사용 횟수가 충분하면 일회용품을 대체하는 효과가 커진다.',main:'다회용기의 효과는 반복 사용과 회수·세척 과정까지 따져 판단해야 한다.',wrong:['다회용기는 사용 횟수와 무관하게 항상 환경 부담이 작다.','운송 거리는 다회용기의 효과에 영향을 주지 않는다.','회수 여부는 일회용품 대체 효과와 무관하다.','세척 과정은 환경 평가에서 제외해야 한다.'],detail:'회수 동선이 짧고 반복 사용 횟수가 충분하면 대체 효과가 커진다.'},
 {theme:'공공 데이터',p:'공공 데이터를 공개하면 시민과 기업이 새로운 서비스를 만들 기회가 생긴다. 그러나 형식이 서로 다르거나 갱신 시점이 불분명하면 자료를 연결하고 해석하기 어렵다. 공개 건수만 늘리는 정책보다 표준 형식과 갱신 주기를 함께 정비하는 정책이 활용도를 높일 수 있다.',main:'공공 데이터의 활용도를 높이려면 공개뿐 아니라 표준화와 갱신 관리가 필요하다.',wrong:['공개 데이터의 건수가 많으면 활용도는 자동으로 높아진다.','자료 형식의 차이는 데이터 연결에 영향을 주지 않는다.','갱신 시점을 알리는 것은 자료 이용에 불필요하다.','표준 형식은 데이터 활용 기회를 줄인다.'],detail:'형식이 다르거나 갱신 시점이 불분명하면 자료 연결과 해석이 어렵다.'},
 {theme:'도서관 공간',p:'도서관의 역할이 자료 보관에 한정되지 않으면서 조용히 읽는 공간과 함께 토론·제작 활동을 위한 공간도 요구되고 있다. 두 기능은 서로 방해할 수 있으므로 공간을 단순히 넓히기보다 이용 시간과 소음 수준에 따라 구역을 나누고 예약 방식을 설계하는 편이 효과적이다.',main:'변화한 도서관의 이용 목적에 맞춰 공간과 운영 방식을 함께 설계해야 한다.',wrong:['도서관은 자료 보관 기능만 유지해야 한다.','토론 공간과 열람 공간은 같은 방식으로 운영해야 한다.','공간의 구역 구분은 이용자 갈등을 키우기만 한다.','도서관 면적을 넓히면 운영 설계는 필요 없다.'],detail:'이용 시간과 소음 수준에 따라 구역을 나누고 예약 방식을 설계할 수 있다.'},
 {theme:'지역 축제',p:'지역 축제의 방문객 수는 행사 규모를 보여 주지만 지역에 남는 경제적 효과를 그대로 나타내지는 않는다. 당일 방문객이 많아도 숙박이나 지역 상점 이용이 적으면 소비가 지역 밖으로 빠져나갈 수 있다. 축제의 성과를 평가할 때는 방문객 수와 체류 시간, 지역 내 소비를 함께 살펴야 한다.',main:'지역 축제는 방문객 수뿐 아니라 체류와 지역 내 소비를 함께 평가해야 한다.',wrong:['방문객 수가 많으면 지역 내 소비도 반드시 크다.','숙박과 상점 이용은 축제 성과와 관계가 없다.','축제 규모가 작으면 경제 효과가 없다.','당일 방문객은 지역 소비를 만들 수 없다.'],detail:'숙박이나 지역 상점 이용이 적으면 소비가 지역 밖으로 빠져나갈 수 있다.'},
 {theme:'식품 표시',p:'식품 포장에 정보가 많아도 소비자가 중요한 내용을 빠르게 찾기 어려우면 표시의 효용은 낮다. 글자 크기와 정보 배치, 용어의 일관성이 이해에 영향을 준다. 표시를 개선할 때에는 제공 정보의 양만 늘리기보다 구매 판단에 필요한 정보가 눈에 띄도록 구성해야 한다.',main:'식품 표시는 정보량보다 필요한 정보를 쉽게 찾고 이해할 수 있게 설계해야 한다.',wrong:['정보량이 많으면 소비자의 이해도도 반드시 높아진다.','글자 크기와 배치는 표시의 이해에 영향을 주지 않는다.','용어의 일관성은 구매 판단과 무관하다.','표시 정보는 가능한 한 작게 배치하는 것이 좋다.'],detail:'구매 판단에 필요한 정보가 눈에 띄도록 구성해야 한다.'},
 {theme:'도심 물류',p:'도심 배송을 빠르게 하려면 차량을 늘리는 방법만 있는 것은 아니다. 공동 집배송 거점을 두면 여러 업체의 배송 경로가 겹치는 일을 줄일 수 있다. 다만 거점의 위치가 수요지에서 멀거나 운영 시간이 맞지 않으면 추가 이동이 생길 수 있으므로, 물량과 시간대에 맞춘 설계가 필요하다.',main:'도심 배송 효율은 차량 수보다 공동 거점의 위치와 운영 설계에 좌우될 수 있다.',wrong:['차량 수를 늘리는 것만이 배송 속도를 높이는 방법이다.','공동 집배송은 경로 중복을 줄일 수 없다.','거점의 위치와 운영 시간은 배송 효율에 영향이 없다.','물량이 적을수록 거점을 멀리 두는 것이 유리하다.'],detail:'거점이 수요지에서 멀거나 운영 시간이 맞지 않으면 추가 이동이 생길 수 있다.'}
];
function lang(){const d=pick(datasets), mode=rand(3);let type,q,ans,wrong;
 if(mode===0){type='중심 내용';q='윗글의 중심 내용으로 가장 적절한 것은?';ans=d.main;wrong=d.wrong;}
 else if(mode===1){type='세부 내용(일치 판단)';q='윗글의 내용과 일치하는 것은?';ans=d.detail;wrong=d.wrong;}
 else {type='추론·이해';q='윗글의 관점에서 타당한 판단은?';ans=d.main;wrong=d.wrong;}
 const ch=choices(ans,wrong,x=>x);return item('lang',type,mode===1?'기초':'표준',q,ch.choices,ch.answer,`지문은 ${d.theme}에 관해 설명합니다. 핵심은 “${ans}”입니다.`,[d.theme,d.p]);}
function data(){const base=rand(0,30)+90, xs=[0,1,2].map(()=>rand(0,30)+50), ys=xs.map(x=>x+rand(5,25));const sum=xs.reduce((a,b)=>a+b,0), total=ys.reduce((a,b)=>a+b,0);const table={head:['부문','전년','올해'],rows:['가','나','다'].map((k,i)=>[k,xs[i],ys[i]])};let mode=rand(3),ans,q,type,wrong,unit='',i=0;
 if(mode===0){ans=total;q='올해 세 부문의 합계는 얼마인가?';type='수치 계산';wrong=[total+10,total-10,total+20,total-20];}
 else if(mode===1){i=rand(3);const delta=ys[i]-xs[i];ans=delta;q=`${['가','나','다'][i]} 부문의 전년 대비 증가량은 얼마인가?`;type='수치 계산';wrong=[delta+2,delta-2,delta+5,delta-5];unit='';}
 else{const pct=Math.round((total-sum)/sum*100);ans=pct;unit='%';q='세 부문 합계의 전년 대비 증가율은 약 몇 %인가?';type='수치 계산';wrong=[pct+5,Math.max(0,pct-5),pct+10,Math.max(0,pct-10)];}
 const ch=choices(ans,wrong,x=>`${x}${unit}`);return {...item('data',type,mode===0?'기초':'표준',q,ch.choices,ch.answer,mode===2?`전년 합계 ${sum}, 올해 합계 ${total}. 증가율은 (${total}−${sum})÷${sum}×100 ≈ ${ans}%.`:mode===0?`올해 합계는 ${ys.join('+')}=${total}입니다.`:`증가량은 올해 값 ${ys[i]}에서 전년 값 ${xs[i]}를 뺀 ${ans}입니다.`,[]),table};}
function math(){const t=rand(5);let q,type,dif,ans,vals,ex,pass='';
 if(t===0){type='작업량';const rateA=rand(2,6),rateB=rand(2,6);ans=rand(2,6);const jobs=(rateA+rateB)*ans;q=`A는 한 시간에 ${rateA}개, B는 한 시간에 ${rateB}개를 완성한다. 두 사람이 함께 ${jobs}개를 완성하는 데 걸리는 시간은?`;vals=[ans+1,ans+2,Math.ceil(jobs/rateA),Math.ceil(jobs/rateB)];ex=`함께 하는 시간당 작업량은 ${rateA}+${rateB}=${rateA+rateB}개입니다. ${jobs}÷${rateA+rateB}=${ans}시간.`;pass='두 사람의 작업 속도는 일정하다.';}
 else if(t===1){type='가격·이익';let cost=rand(10,40)*1000,pct=rand(10,40),price=cost*(100+pct)/100,disc=rand(10,30);ans=price*(100-disc)/100;q=`원가 ${cost.toLocaleString()}원인 상품에 원가의 ${pct}%를 더해 정가를 정했다. 정가에서 ${disc}% 할인해 판매할 때 판매가는?`;vals=[ans+1000,ans-1000,price,ans+2000];ex=`정가는 ${cost.toLocaleString()}×${100+pct}%=${price.toLocaleString()}원, 판매가는 정가의 ${100-disc}%인 ${ans.toLocaleString()}원.`;pass='';}
 else if(t===2){type='거리·속력·시간';let v=rand(30,90),h=rand(2,5),d=v*h;ans=v;q=`한 차량이 ${d}km를 ${h}시간 동안 일정한 속력으로 이동했다. 평균 속력은?`;vals=[v+10,v-10,v*2,Math.round(d/(h+1))];ex=`평균 속력=${d}÷${h}=${v}km/h.`;}
 else if(t===3){type='방정식·응용';let x=rand(8,25),y=rand(5,18);ans=x;q=`두 수의 합은 ${x+y}이고 큰 수에서 작은 수를 뺀 값은 ${x-y}이다. 큰 수는?`;vals=[y,x+y,x-1,y+1];ex=`큰 수를 x, 작은 수를 y라 두면 x+y=${x+y}, x−y=${x-y}. 두 식을 더해 2x=${2*x}, 따라서 x=${x}.`;}
 else {type='확률·경우의 수';let r=rand(2,5),b=rand(3,6),tot=r+b;ans=r/tot;q=`빨간 공 ${r}개와 파란 공 ${b}개가 든 주머니에서 공 한 개를 무작위로 꺼낼 때, 빨간 공일 확률은?`;vals=[(r+1)/tot,r/(tot+1),b/tot,1/(tot)];ex=`전체 ${tot}개 중 빨간 공이 ${r}개이므로 확률은 ${r}/${tot}=${ans}.`;pass='모든 공은 뽑힐 가능성이 같다.';}
 const ch=choices(ans,vals,x=>typeof x==='number'&&(t===0||t===1||t===2||t===3)?(t===0?`${x}시간`:t===1?`${x.toLocaleString()}원`:t===2?`${x}km/h`:`${x}`):String(x));return item('math',type,t<2?'표준':'기초',q,ch.choices,ch.answer,ex,pass?[pass]:[]);}
function logic(){const names=['가','나','다','라','마'];const order=shuffled(names);let constraints=[`${order[0]}의 발표가 ${order[1]}보다 먼저다.`,`${order[1]}의 발표가 ${order[2]}보다 먼저다.`,`${order[3]}의 발표가 ${order[4]}보다 먼저다.`];let trueText=`${order[0]}의 발표가 ${order[2]}보다 먼저다.`;let falseTexts=[`${order[2]}의 발표가 ${order[0]}보다 먼저다.`,`${order[1]}의 발표가 ${order[0]}보다 먼저다.`,`${order[4]}의 발표가 ${order[3]}보다 먼저다.`,`${order[2]}의 발표가 ${order[1]}보다 먼저다.`];let all=[trueText,...falseTexts.slice(0,4)],ch=choices(trueText,all.filter(x=>x!==trueText),x=>x); // choices helper expects only distractors
 return item('logic','순서·순위','표준','다섯 발표자가 각자 한 번씩 발표한다. 조건으로부터 반드시 참인 것은?',ch.choices,ch.answer,`조건에 따라 ${order[0]}→${order[1]}→${order[2]}의 순서가 확정됩니다. 따라서 정답 진술은 반드시 참입니다.`,constraints);}
const seqPatterns=[()=>{let a=rand(1,10),d=rand(2,6),v=[0,1,2,3,4,5,6,7,8].map(i=>a+d*i);return {v,answer:v[4],desc:`매번 ${d}씩 증가`,type:'등차 수열',dif:'기초'};},()=>{let a=rand(1,4),m=2,v=[0,1,2,3,4,5,6,7,8].map(i=>a*Math.pow(m,i));return {v,answer:v[4],desc:'매번 2배',type:'등비 수열',dif:'기초'};},()=>{let a=rand(1,4),v=[0,1,2,3,4,5,6,7,8].map(i=>(i+1)*(i+1)+a);return {v,answer:v[4],desc:`n²+${a}`,type:'제곱수 응용',dif:'표준'};},()=>{let a=rand(1,5),b=rand(12,19),d=rand(1,3),e=rand(1,3),v=[0,1,2,3,4,5,6,7,8].map(i=>i%2===0?a+(i/2)*d:b-Math.floor(i/2)*e);return {v,answer:v[4],desc:`홀수항은 ${d}씩 증가하고 짝수항은 ${e}씩 감소`,type:'교대 규칙',dif:'표준'};},()=>{let a=rand(1,3),b=rand(2,5),v=[a,b];while(v.length<6)v.push(v.at(-1)+v.at(-2));return {v,answer:v[4],desc:'앞의 두 항의 합',type:'점화 규칙',dif:'표준'};}];
function seq(){let r=pick(seqPatterns)();if(Math.random()<0.28){let n=rand(6,9),answer=r.v[n-1],shown=r.v.slice(0,5).join('   ');const ch=choices(answer,[r.v[n-2],answer+1,answer-1,answer+2],String);return item('seq','N번째 항',r.dif,`수열 ${shown} … 의 규칙에 따라 ${n}번째 항은?`,ch.choices,ch.answer,`규칙은 ${r.desc}입니다. 첫째 항부터 ${n}번째까지 적용하면 ${answer}입니다.`,[],shown+'   …');}let idx=rand(2,4),answer=r.v[idx],shown=r.v.map((v,i)=>i===idx?'( )':String(v));const ch=choices(answer,[answer+1,answer-1,answer+2,answer-2],String);return item('seq',r.type,r.dif,`다음 수열의 빈칸에 들어갈 수는?
${shown.join('   ')}`,ch.choices,ch.answer,`규칙은 ${r.desc}입니다. 따라서 빈칸은 ${answer}입니다.`,[],shown.join('   '));}
const makers={lang,data,math,logic,seq};
function generate(area,n=10){return Array.from({length:n},()=>makers[area]());}
function attach(){if(typeof AREA_DEFS==='undefined')return;const descriptions={lang:'지문 중심 내용·세부 일치와 근거 추론을 짧은 지문으로 연습합니다.',data:'표를 읽고 합계·증가량·증가율을 계산합니다. 단위와 기준값을 확인하세요.',math:'작업량·가격·속력·방정식·확률의 기본 응용을 풉니다.',logic:'순서 조건을 정리해 반드시 참인 관계를 찾습니다.',seq:'등차·등비·제곱·교대·점화 규칙을 풉니다. N번째 항은 6~9번째까지만 묻습니다.'};AREA_DEFS.forEach(a=>{a.desc=descriptions[a.key]||a.desc;a.build=n=>typeof mixBuild==='function'?mixBuild(a.key,n,k=>generate(a.key,k)):generate(a.key,n);});const d=document.querySelector('.disclaimer');if(d)d.textContent='이 연습실은 SKCT 공개 유형 안내와 참고 자료의 유형·시간 압박 특성을 바탕으로 새로 작성한 연습 문항을 제공합니다. 교재·유료 모의고사 문항을 복제하지 않으며, 실제 시험과 동일한 문항 또는 난도를 보장하지 않습니다.';}
function toBankItem(q){const p=(q.p||[]).slice();if(q.table){p.push('자료 표: '+q.table.head.join(' / '));q.table.rows.forEach(r=>p.push(r.join(' / ')));}return {area:q.area,q:q.q,p,c:q.choices,a:q.answer,e:q.explain,_meta:{skill:q.qtype,difficulty:q.difficulty,topic:q.qtype,source_basis:'SKCT 공개 유형표와 업로드 자료의 유형·시간 압박 분석을 참고해 새로 작성'}};}
const api={generate,attach,toBankItem,areas:AREAS};root.SKCTFactory=api;
if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
